[[headers]]
  for = "/*"
  [headers.values]
    access-control-allow-origin = "*"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=()"
    X-Frame-Options = "SAMEORIGIN"
    Content-Security-Policy = script-src 'self'